name: "pnpm package dependencies"
description: "Output dependencies needed to filter git commits"
author: "Lab Digital"

inputs:
  package:
    description: "Package name"
    required: true

# Define your outputs here.
outputs:
  paths:
    description: "List of git filter paths"

runs:
  using: node20
  main: dist/index.js
